"""
WMATICTASwapRSI Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import WMATICTASwapRSIStrategy
except ImportError:
    from strategy import WMATICTASwapRSIStrategy

__all__ = [
    "WMATICTASwapRSIStrategy",
]
